// Components/Terms/TermsPage.jsx

import React from 'react';
import './TermsPage.scss';

const terms = `
This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name  “www.sadhanacart.com”, including the related mobile site and mobile application

The Platform is owned by Sadhana Cart Private Limited, a company incorporated under the Companies Act, 2025 with its registered office at Floor No.: GROUND FLOOR SRI MUKUNDA SRI GANESH RESIDENCY
Building No./Flat No.: FLAT NO.3 M.NO.1-11-400, 1-11-400/1, 1-11-399, 1-
11-399/1
Road/Street: NIJALINGAPPA NAGAR, City/Town/Village : RAICHUR,District : RAICHUR,State : KARNATAKA, Pin Code: 584101

Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with Sadhana Cart Private Limited and these terms and conditions including the policies constitute Your binding obligations, with Sadhana Cart.

For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Sadhana Cart allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Sadhana Cart Private Limited.

ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Sadhana Cart Policies (including but not limited to Privacy Policy available at Privacy) as amended from time to time.

Membership Eligibility

Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/permission of a parent or legal guardian.

As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. Sadhana Cart reserves the right to terminate your membership and/or refuse to provide you with access to the Platform if it is brought to Sadhana Cart's notice or if it is discovered that You are under the age of 18 years and transacting on the Platform.

Your Account and Registration Obligations

If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.

Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through a onetime password verification.

You agree that Sadhana Cart shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Website Platform.

If You share or allow others to have access to Your account on the Platform (“Account”), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information. You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences therefrom.

You must maintain confidentiality of the account information and for all the activities that occur under Your account. You must not share your login details, i.e., username and password of Your account with any other person, else it would be considered breach of this Terms of Use.

You agree to: (a) ensure that You successfully log out from Your account at the end of each session; and (b) immediately notify Sadhana Cart of any unauthorized use of Your account. If there is reason to believe that there is likely to be a breach of security or misuse of Your account, We may request You to change the password or we may suspend Your account without any liability to Sadhana Cart, for such period of time as we deem appropriate in the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.

You will have access to other apps owned by Sadhana Cart group companies through the same login username and password. You agree to have single login access to all the apps owned by Sadhana Cart group companies.

Communications

When You use the Platform or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.

Platform for Transaction and Communication

The Platform enables the Buyer and Seller to transact on the Platform. Sadhana Cart is not and cannot be a party to or control in any manner any transaction between the Platform's Users.
`;

const TermsPage = () => {
  const formatText = (text) => {
    return text.split('\n\n').map((paragraph, index) => {
      if (paragraph.trim().length === 0) return null;
      if (paragraph === paragraph.toUpperCase()) {
        return <h3 key={index}>{paragraph}</h3>;
      }
      return <p key={index}>{paragraph}</p>;
    });
  };

  return (
    <div className="terms-page">
      <h2>Terms & Conditions</h2>
      {formatText(terms)}
    </div>
  );
};

export default TermsPage;
